### ISSUE TITLE
Placement Width and Height Return is Zero In Dynamic Size Zone

### ISSUE THREAD

**Issue by philipborbon** [sparklit/adbutler-android-sdk#1]
PlacementRequestConfig config = new PlacementRequestConfig.Builder(170188, 273944, 320, 75).build();

    AdButler adbutler = new AdButler();
    adbutler.requestPlacement(config, new PlacementResponseListener() {
        @Override
        public void success(PlacementResponse placementResponse) {
            List<Placement> placementList = placementResponse.getPlacements();

            if ( !placementList.isEmpty() ){
                final Placement placement = placementList.get(0);

                if ( placement != null ){
                    if ( BuildConfig.DEBUG ){
                        Log.e(LOG_TAG, String.format(Locale.US, "Placement Width:(%d) Height:(%d)", placement.getWidth(), placement.getHeight()));
                    }
                }
            }
        }
    }

**Comment by nwehnin** [comment]
#1

**Comment by sanakhet** [comment]
Thanks for the reminder, the dimensions returned should be those of the selected ad - we're going to fix that shortly, and I'll update this issue again once complete.

**Comment by sanakhet** [comment]
For now - as a work around - I'd recommend adding banners to campaigns in Advertisers, rather than in the zone directly.

**Comment by sanakhet** [comment]
We've made a change to the behavior of images in Dynamic Zones. I'd recommend contacting support directly for further help with your account regarding this issue!
