### ISSUE TITLE
Ads Are Not Using Ad Serving Domain

### ISSUE THREAD

**Issue by philipborbon** [sparklit/adbutler-android-sdk#5]
We have setuped "Ad Serving Domain" in Adbutler Admin.

Placement's "redirectUrl" is still using "servedbyadbutler.com".

**Comment by wprevett** [comment]
Try updating to release 1.0.3.

There will be a new setter when you instantiate the AdButler object.

`AdButler adbutler = new AdButler();`
`adbutler.setDomain("yourdomain.com");`
`adbutler.requestPlacement(config, new PlacementResponseListener() { ...etc`

**Comment by philipborbon** [comment]
Tried the update and is working in my end. Thanks.

**Comment by philipborbon** [comment]
By any chance, will similar update be also added in iOS SDK and Wordpress Plugin?
We're experiencing same issue in the said platform.

**Comment by wprevett** [comment]
Hi Philip

I will add this to iOS early this week.

I spoke to one of our wordpress plugin developers, he suggests that if you created your custom domain after you set up wordpress, then you should re-enter your wordpress API key and save it again.

**Comment by philipborbon** [comment]
Hi William

Re-entering Wordpress API Key and re-assigning the ad zones in sidebar widget worked for me.
I'm looking forward to the iOS SDK update.

Thanks for the help.

Closing this issue now.
